package com.gmapssimple;

import java.util.ArrayList;
import java.util.concurrent.ExecutionException;


import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.util.Base64;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;

public class Adapter extends BaseAdapter {
	private static int itemDetailsrrayList;
	Bitmap[] bitmapArray;
	int currentimageindex=0;
	
	//Bitmap[] array1=ListViewActivity.array;
	
	/**String a="/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAHMAzMDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcIC"
			+"QoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0"
			+"RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD2aiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
	+"gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAqv"
	+"LfW0Ehjkl2sO2CasVz+qf8hCT8P5UG9CmqkrM3Y5EljEkbblboafVTTP+QfF+P8AM1boMprlk0FF"
	+"FFBIUUUUAFFFFABRRRQAUUUUAFFZWr3E0UiRxuyAjJKnGaNIuZpJJI5HZxjILHOKDf2D9nz3NWii"
	+"igwCiiigBkkiRRmR22qvU1FDfW08nlxy5Y9sEUzUv+QfL+H86ydL/wCQhH+P8jQdNOjGVOU30Oho"
	+"oooOYKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACi"
	+"iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK"
	+"KACiiigAooooAKKKKACiiigAooqK4nS2hMr5wOw70DSbdkS0VhTavcOf3e2Iewyf1qPOonn/AEr/"
	+"AMeoOpYWVveaR0NFc9FqN3AceYWweVfn/wCvWzZ3aXkRZRtZeGX0oM6lCVNXexYoorP1S6mtlj8l"
	+"9u7OeAaDOEHOXKjQorNtdQIsWmuX3MHKjAAJ4FUZ9UuZidreWvovX86DWOGnJtdjoKK5pL26Rtwn"
	+"cn3OR+ta+n6gLrMcgCyAZ46NQOphpwV9y9RRRQcwUVk3mrMGMdtjA6v1/Ks83lySSbiTn0Yig6oY"
	+"Wcld6HTVz+qf8hCT8P5U+21aaIhZj5ie/UVFqEiS3jyIwZSBg/hSNqFGVOpr2NfTP+QfF+P8zVuq"
	+"mmf8g+L8f5mrVM46vxy9RaKw7fUrqS6jVpAVZwCNo7mpr/VGDmK3OMcM/wDhQavDT5uU1qK5pb26"
	+"RgwuJMj1bI/WuiiYvEjHqVBNBNWi6drsfRUF1dx2ke5zkn7qjqax5tUupiQjeWp4AXr+dAU6E6mq"
	+"2N+iue/4mIGT9q/8ep0Gq3MRG5vMUdm6/nQaPCyt7rTN+ioLW6ju4t6cEcMp6ip6DlaadmRT20Ny"
	+"AJUDY6c4ogtobYERIFz175qpql1NbLH5TbdxOTgGl0u6muUk85txUjBwBQbck/Zc19C/RRVe7u0t"
	+"ItzcsfuqO9BjGLk7IsUVz02pXUx/1hQZ6Jxj+tMS+uo23Cdz/vHI/Wg61g523NnUv+QfL+H86ydL"
	+"/wCQhH+P8jVmTUVurCWOQBJcDgdG57VW0v8A5CEf4/yNC3NacJQozUvP8joaKKKDzgooooAKKKKA"
	+"CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACoLu2F3AYi23kEHGanooGm4u6K9tZQWo/drlv7x5NWKqz6jbW5Ks+5h1VeaqNrahjtty"
	+"R2JbB/lQbKlVqa2JdXgV7YzYG9Mc+o9KpaRIVvdvZ1I/rTrjVvtFu8Xkbdw6784/SodL/wCQhH+P"
	+"8jQjrhCUaEozOhrK1vpD+P8AStWsrW+kP4/0pM5MN/FRn2ttJdyiNThRyT2Fb9vaw2y4jQZ7sep/"
	+"GqGifdm+o/rWrTNMTUk5uPQqX1mlzCxCjzAMqw6/SsO3kMNxHIDjawrp65WQYkYehNHU1wknKLiz"
	+"qqpapOYbQhThpDt/DvVwfdH0rI1tv3kS+gJpM5aEeaokynZW32q4EecKOWPtXQxxRwpsjQKvoKzd"
	+"EQbZX75ArVpmmKm3Pl6Ip3enRXKllASTsw7/AFrBkjaKRkcYZTgiuqrn9U/5CEn4fypGuEqSb5Wa"
	+"umf8g+L8f5mrXaqumf8AIPi/H+Zq12ps5Kn8SXqcqCQcg4I71q6Zp6lBPMobP3FP86yl5YD3rqgA"
	+"AABgDtQjvxVRxikuojxpIu2RFcejDNLwq+gApar3zFLKYj+7ig86KbaRhXU7XVy0h5ycKPQdq27K"
	+"yS1iHAMhHzN/SsWxUPexA/3ga6ShHZipcqUFsFUdSsknhaVVAkUZyO49KvUlBxwm4SujnbC4NvdK"
	+"2flY7W+ldHXLSLtldR2YiumiYtEjHqVBoWx2YuKupGbrfSH8f6UaJ92b6j+tGt9Ifx/pRon3ZvqP"
	+"60If/ML/AF3NWucv5zPduc/Kp2r9BXQudsbN6AmuXRd7qvqcUuosHFXcjZ02xSOJZpFDSNyMj7o7"
	+"fjV6SKOVNsiBl9CKcAAMDoKWmck6kpS5mYOoaebY+ZHkxE/980zS/wDkIR/j/I1ral/yD5fw/nWT"
	+"pf8AyEI/x/kaSO+nNzoSv5nQ0UUUzzQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACii"
	+"igAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKK"
	+"ACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACs/VbpoIRGhw0nf0FaFY2tg+dE3"
	+"YqR+tJm+HipVEmVrKya8cjO1F+81aqaVaKuChc+pY5/SoNEdfLlj43Zz+FalM1xFWam4p2M290+1"
	+"itJJEiwyjg7j61Q0v/kIR/j/ACNaGq3caQNbg7nbqB/DWfpf/IQj/H+RoW5rS5nQk5ef5HQ1la30"
	+"h/H+latZWt9Ifx/pSZy4b+Kg0T7s31H9a1aytE+7N9R/WtWmGI/isK5aX/XP/vGuprlpf9c/+8aX"
	+"U3we8jqF+6PpWRrY/exH/ZNa6/dH0rP1iEvbLIBzGefof8imzDDu1VDNEYeXKvcEGtSuf025Ftc/"
	+"OcI4wT6e9b4IIBByD3oKxMWqjfcWuf1T/kISfh/Kti6vIrRMscv2QdTXPTSvPK0jnLMaRrhISu5d"
	+"De0z/kHxfj/M1a7VV0z/AJB8X4/zNWu1NnLU/iS9Tll+8PrXVVyq/eH1rqqDrxn2QqtqAzYzAf3c"
	+"1ZproJI2Q9GBBoOKLtJM52xbZewn/aA/OukrlnR4Jih4ZDXQWV4l3EMECQD5loR24uLdpos0lLVD"
	+"Ur5IYmiRgZGGOP4RQccIOcrIxZG3ysw7sTXTRKViRT1CgVz9hbm4u0XHyqdzfSujoWx14uSuooyt"
	+"b6Q/j/SjRPuzfUf1o1vpD+P9KNE+7N9R/WhD/wCYX+u5pSDMTgd1NcxG22RWPYg11VczdQmC5kjx"
	+"gA8fTtS6iwbXvROmoqpp90txbqCf3iDDD+tWiQoJJAA6k0zjlFxdmVdS/wCQfL+H86ydL/5CEf4/"
	+"yNT6lqAmBghPyfxN/e/+tUGl/wDIQj/H+RpI9CnBwoSv5nQ0UUUzzQooooAKKKKACiiigAooooAK"
	+"KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
	+"ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACq95"
	+"ardwFCcMOVPoasUUDjJxd0c3JBc2b7irIQeHXp+dSC/vpv3ayMxPZFGf0FdBRQdf1pP4opsxrfSp"
	+"Cjy3Gd20lUzyT70zTbadL5GeF1UZyWUjtW5RQQ8TNpp9QrN1iGWVYvLjZ8E52jNaVFBjTnySUkZu"
	+"jwyRJL5kbJkjG4YrSoooCpPnk5MK5yS0uTM+IJD8x52nHWujooLpVnSvZCDgCkZVdSrDIIwRTqKD"
	+"EwbvTJoXJiVpIyeMDJH1qqk80a7UldR6KxFdRRQdkcW7WkrmBb6dcXL7pAyKTks/U0/ULFo5UW3h"
	+"dkCAZVc85PWtyign61PmuVtPRo7GNXUqwzkH6mrHalooOeT5m2c2tnc+YB5EnX+6cV0lFFBpVrOr"
	+"a6CiiigxKN/pwuvnQhZB3PQ/WseS2uLc5eNkwfvdvzrpqKDppYmUFbdHMG6uCMGeUg/7ZqWDT7md"
	+"uIyi/wB5xgV0VFBo8W7e7GxBaWsdpFsTkn7zHuanoooONtyd2ZusQyyrF5cbPgnO0Zo0eGSJJfMj"
	+"ZMkY3DFaVFBr7Z+z9nYKpahYC6UOhAlUcZ7j0q7RQZwk4O6OYeKa2cb1eNgeD0/I04G6uzsDSy4P"
	+"QkkCulooOv63/d1MmHSjHbSPIN8pQ7VHY4/nUOm206XyM8LqozkspHatyigz+sTs0+oUUUUHMFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
	+"FABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUU"
	+"AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA"
	+"UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
	+"RRQAUUUUAFFFFABRRRQAUUUUAf/Z";
	byte[] decodedString = Base64.decode(a, Base64.DEFAULT);
	Bitmap bitmap4=BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);*/
	
	
	
	private Integer[] imgid = {
			R.drawable.markerblue,
			R.drawable.hiking,
			
			};
	
	private LayoutInflater l_Inflater;

	public Adapter(Context context,int results,Bitmap[] b) {
		itemDetailsrrayList = results;
		bitmapArray=b;
		l_Inflater = LayoutInflater.from(context);
	}
	public Bitmap[] getBitmap(){
		return bitmapArray;
	}

	public int getCount() {
		return itemDetailsrrayList;
	}

	public Object getItem(int position) {
		return itemDetailsrrayList;
	}

	public long getItemId(int position) {
		return position;
	}

	public View getView(int position, View convertView, ViewGroup parent) {
		ViewHolder holder;
		if (convertView == null) {
			convertView = l_Inflater.inflate(R.layout.item_details_view, null);
			holder = new ViewHolder();
			//holder.txt_itemName = (TextView) convertView.findViewById(R.id.name);
			//holder.txt_itemDescription = (TextView) convertView.findViewById(R.id.itemDescription);
			//holder.txt_itemPrice = (TextView) convertView.findViewById(R.id.price);
			holder.itemImage = (ImageView) convertView.findViewById(R.id.photo);

			convertView.setTag(holder);
		} else {
			holder = (ViewHolder) convertView.getTag();
		}
		
		//holder.txt_itemName.setText(itemDetailsrrayList.get(position).getName());
		//holder.txt_itemDescription.setText(itemDetailsrrayList.get(position).getItemDescription());
		//holder.txt_itemPrice.setText(itemDetailsrrayList.get(position).getPrice());
		Bitmap[] bitmap4 = getBitmap();
		Log.i("tag", bitmap4.toString());
		holder.itemImage.setImageBitmap(bitmap4[currentimageindex%bitmap4.length]);
		currentimageindex++;
//		imageLoader.DisplayImage("http://192.168.1.28:8082/ANDROID/images/BEVE.jpeg", holder.itemImage);

		return convertView;
	}

	static class ViewHolder {
		TextView txt_itemName;
		TextView txt_itemDescription;
		TextView txt_itemPrice;
		ImageView itemImage;
	}
}

